name: educonnect_app
description: EduConnect - Educational Platform Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  dio: ^5.3.2
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2
  fl_chart: ^0.65.0
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  animations: ^2.0.8
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/